# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogcategory',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='catalogcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.DeleteModel(
            name='CatalogCategory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
