# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_catalog_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='publisher',
        ),
    ]
