# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170720_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_in_dollars',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(max_length=300),
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([('id', 'slug')]),
        ),
    ]
