# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170721_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d'),
        ),
    ]
